# Generated by Django 3.2.13 on 2022-05-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_iot_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leo_topic', models.TextField()),
            ],
        ),
    ]
